package com.octopus.affiliate.admin.db.dao;

import com.octopus.affiliate.admin.db.model.AffiliateUser;
import com.octopus.affiliate.admin.db.model.AffiliateUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AffiliateUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    long countByExample(AffiliateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    int deleteByExample(AffiliateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    int insert(AffiliateUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    int insertSelective(AffiliateUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AffiliateUser selectOneByExample(AffiliateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AffiliateUser selectOneByExampleSelective(@Param("example") AffiliateUserExample example, @Param("selective") AffiliateUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<AffiliateUser> selectByExampleSelective(@Param("example") AffiliateUserExample example, @Param("selective") AffiliateUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    List<AffiliateUser> selectByExample(AffiliateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AffiliateUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AffiliateUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    AffiliateUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") AffiliateUser record, @Param("example") AffiliateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    int updateByExample(@Param("record") AffiliateUser record, @Param("example") AffiliateUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    int updateByPrimaryKeySelective(AffiliateUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    int updateByPrimaryKey(AffiliateUser record);
}