package com.octopus.affiliate.admin.db.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class AffiliateUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.id
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.name
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.password
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.email
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.phone
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.qq
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.status
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.role
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.l_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private Date lTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.c_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.u_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private Date uTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiliate_user.accept_status
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    private Boolean acceptStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.id
     *
     * @return the value of affiliate_user.id
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.id
     *
     * @param id the value for affiliate_user.id
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.name
     *
     * @return the value of affiliate_user.name
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.name
     *
     * @param name the value for affiliate_user.name
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.password
     *
     * @return the value of affiliate_user.password
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.password
     *
     * @param password the value for affiliate_user.password
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.email
     *
     * @return the value of affiliate_user.email
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.email
     *
     * @param email the value for affiliate_user.email
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.phone
     *
     * @return the value of affiliate_user.phone
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.phone
     *
     * @param phone the value for affiliate_user.phone
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.qq
     *
     * @return the value of affiliate_user.qq
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.qq
     *
     * @param qq the value for affiliate_user.qq
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.status
     *
     * @return the value of affiliate_user.status
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.status
     *
     * @param status the value for affiliate_user.status
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.role
     *
     * @return the value of affiliate_user.role
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.role
     *
     * @param role the value for affiliate_user.role
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.l_time
     *
     * @return the value of affiliate_user.l_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public Date getlTime() {
        return lTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.l_time
     *
     * @param lTime the value for affiliate_user.l_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setlTime(Date lTime) {
        this.lTime = lTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.c_time
     *
     * @return the value of affiliate_user.c_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.c_time
     *
     * @param cTime the value for affiliate_user.c_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.u_time
     *
     * @return the value of affiliate_user.u_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.u_time
     *
     * @param uTime the value for affiliate_user.u_time
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiliate_user.accept_status
     *
     * @return the value of affiliate_user.accept_status
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public Boolean getAcceptStatus() {
        return acceptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiliate_user.accept_status
     *
     * @param acceptStatus the value for affiliate_user.accept_status
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    public void setAcceptStatus(Boolean acceptStatus) {
        this.acceptStatus = acceptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", phone=").append(phone);
        sb.append(", qq=").append(qq);
        sb.append(", status=").append(status);
        sb.append(", role=").append(role);
        sb.append(", lTime=").append(lTime);
        sb.append(", cTime=").append(cTime);
        sb.append(", uTime=").append(uTime);
        sb.append(", acceptStatus=").append(acceptStatus);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AffiliateUser other = (AffiliateUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRole() == null ? other.getRole() == null : this.getRole().equals(other.getRole()))
            && (this.getlTime() == null ? other.getlTime() == null : this.getlTime().equals(other.getlTime()))
            && (this.getcTime() == null ? other.getcTime() == null : this.getcTime().equals(other.getcTime()))
            && (this.getuTime() == null ? other.getuTime() == null : this.getuTime().equals(other.getuTime()))
            && (this.getAcceptStatus() == null ? other.getAcceptStatus() == null : this.getAcceptStatus().equals(other.getAcceptStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affiliate_user
     *
     * @mbg.generated Mon Jun 25 17:57:25 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        result = prime * result + ((getlTime() == null) ? 0 : getlTime().hashCode());
        result = prime * result + ((getcTime() == null) ? 0 : getcTime().hashCode());
        result = prime * result + ((getuTime() == null) ? 0 : getuTime().hashCode());
        result = prime * result + ((getAcceptStatus() == null) ? 0 : getAcceptStatus().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table affiliate_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        password("password", "password", "VARCHAR", true),
        email("email", "email", "VARCHAR", false),
        phone("phone", "phone", "VARCHAR", false),
        qq("qq", "qq", "VARCHAR", false),
        status("status", "status", "BIT", true),
        role("role", "role", "VARCHAR", true),
        lTime("l_time", "lTime", "TIMESTAMP", false),
        cTime("c_time", "cTime", "TIMESTAMP", false),
        uTime("u_time", "uTime", "TIMESTAMP", false),
        acceptStatus("accept_status", "acceptStatus", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table affiliate_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}